#!/usr/bin/env zsh
if [[ -z $STOW_FOLDERS ]]; then
  STOW_FOLDERS="linux,gitconfig,nvim,tmux"
fi

if [[ -z $DORFILES ]]; then
 DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
