#!/usr/bin/env bash 

config_dir="install"

if [[ -z $DOTFILES ]]; then
 DOTFILES=$HOME/.dotfiles
fi

folders_list=""

common_folders=$(cat $DOTFILES/$config_dir/folders-common.txt | tr "\n" ,)
folders_list+=$common_folders

if [[ $INSTALL_OS ]]; then
  os_folders=$(cat $DOTFILES/$config_dir/folders-$INSTALL_OS.txt | tr "\n" ,)
  folders_list+=$os_folders
fi

# Remove dangling las "," from list of folders if folders_list is not empty
# if [[ -n $folders_list ]]; then
#   folders_list=${folders_list::-1} 
# fi

STOW_FOLDERS=$folders_list DOTFILES=$DOTFILES $DOTFILES/$config_dir/install
